// Configuration file for environment-specific settings
// This file is replaced during deployment with credentials from environment variables

// SECURITY NOTE: For Cloudflare Pages deployment
// This file is automatically generated by build.sh using environment variables:
// - ADMIN_USERNAME (should be set to: Latosha)
// - ADMIN_PASSWORD (should be set to: Ataymia!0)

const CONFIG = {
    // These placeholder values will be replaced during build
    // DO NOT use these in production - set environment variables in Cloudflare Pages
    ADMIN_USERNAME: 'PLACEHOLDER_USERNAME',
    ADMIN_PASSWORD: 'PLACEHOLDER_PASSWORD'
};

// Function to check if credentials match
function validateCredentials(username, password) {
    // Verify that credentials have been properly injected
    if (CONFIG.ADMIN_USERNAME === 'PLACEHOLDER_USERNAME' || CONFIG.ADMIN_PASSWORD === 'PLACEHOLDER_PASSWORD') {
        console.error('Admin credentials not properly configured. Set ADMIN_USERNAME and ADMIN_PASSWORD in Cloudflare Pages environment variables.');
        return false;
    }
    return username === CONFIG.ADMIN_USERNAME && password === CONFIG.ADMIN_PASSWORD;
}

// Function to load credentials from remote source (optional)
async function loadRemoteConfig() {
    try {
        // In production, credentials are injected during build
        return CONFIG;
    } catch (error) {
        console.error('Failed to load remote config', error);
        return CONFIG;
    }
}
